# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Release Nightly

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force run the workflow"
        required: false
        default: "true"
jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Set New Nightly Version and Git Push
      id: newVersion
      run: |
        powershell ./cicd/SetNewNightlyVersion.ps1
        $newVersion = Get-Content .\cicd\NightlyVersion.txt
        echo "newVersion=$newVersion" >> $env:GITHUB_OUTPUT
        git add ./cicd/NightlyVersion.txt
        git commit -m "Update Nightly Version to $newVersion"
        git push
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: DotNet Publish
      run: dotnet publish WimyGit -c Release /p:PublishProfile=ReleasePublishProfile

    - name: Create tag
      id: tag
      run: |
        $tag = "wimygit-nightly-v${{ steps.newVersion.outputs.newVersion }}"
        echo "tag=$tag" >> $env:GITHUB_OUTPUT
        
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        
        git tag $tag --force
        git push origin $tag --force

    - name: Zip build folder
      run: |
        powershell Move-Item WimyGit\bin\Release\publish\WimyGit.exe WimyGit\bin\Release\publish\WimyGitN.exe
        $zipName = "${{ steps.tag.outputs.tag }}.zip"
        powershell Compress-Archive -Path WimyGit\bin\Release\publish\* -DestinationPath $zipName -Force
      shell: pwsh

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        files: ${{ steps.tag.outputs.tag }}.zip
        generate_release_notes: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Winget Publish
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        GH_TOKEN: ${{ secrets.MY_PAT }}
      run: |
        $tag = "${{ steps.tag.outputs.tag }}"
        $packageIdentifier = "Wimysoft.WimyGit.Nightly"
        $newVersion = "${{ steps.newVersion.outputs.newVersion }}"
        $newDownloadUrl = "https://github.com/zelon/wimygit/releases/download/$tag/$tag.zip"
        powershell .\cicd\CreateWingetPullRequet.ps1 submit -packageIdentifier $packageIdentifier -newVersion $newVersion -newDownloadUrl $newDownloadUrl -token $env:GITHUB_TOKEN
